# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x62ug.proto\x12\x08threemon\"L\n\x05\x44\x65\x62ug\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x0b\n\x03pid\x18\x02 \x01(\x04\x12\x0e\n\x06procid\x18\x05 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x0c\"M\n\x03Log\x12\n\n\x02ts\x18\x04 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x05 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x62lob\x18\x03 \x01(\x0c\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _DEBUG._serialized_start=25
  _DEBUG._serialized_end=101
  _LOG._serialized_start=103
  _LOG._serialized_end=180
# @@protoc_insertion_point(module_scope)
