# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="file.proto",
    package="threemon",
    syntax="proto3",
    serialized_options=_b("H\002"),
    serialized_pb=_b(
        '\n\nfile.proto\x12\x08threemon"\xb5\x01\n\x04\x46ile\x12\n\n\x02ts\x18\x07 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12"\n\x04kind\x18\x02 \x01(\x0e\x32\x14.threemon.FileAccess\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\n\n\x02id\x18\x04 \x01(\x04\x12"\n\x05\x66lags\x18\x08 \x01(\x0e\x32\x13.threemon.FileFlags\x12\x0f\n\x07srcpath\x18\x05 \x01(\t\x12\x0f\n\x07\x64stpath\x18\x06 \x01(\t*\x92\x01\n\nFileAccess\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08OpenRead\x10\x01\x12\x0e\n\nOpenModify\x10\x02\x12\x0e\n\nCreateRead\x10\x03\x12\x10\n\x0c\x43reateModify\x10\x04\x12\n\n\x06\x44\x65lete\x10\x05\x12\x11\n\rDeleteDelayed\x10\x06\x12\n\n\x06Rename\x10\x07\x12\x0c\n\x08Truncate\x10\x08*.\n\tFileFlags\x12\x0f\n\x0bNoFileFlags\x10\x00\x12\x10\n\x0c\x44umpContents\x10\x01\x42\x02H\x02\x62\x06proto3'
    ),
)

_FILEACCESS = _descriptor.EnumDescriptor(
    name="FileAccess",
    full_name="threemon.FileAccess",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="Unknown", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="OpenRead", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="OpenModify", index=2, number=2, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="CreateRead", index=3, number=3, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="CreateModify", index=4, number=4, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Delete", index=5, number=5, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="DeleteDelayed", index=6, number=6, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Rename", index=7, number=7, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Truncate", index=8, number=8, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=209,
    serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_FILEACCESS)

FileAccess = enum_type_wrapper.EnumTypeWrapper(_FILEACCESS)
_FILEFLAGS = _descriptor.EnumDescriptor(
    name="FileFlags",
    full_name="threemon.FileFlags",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="NoFileFlags", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="DumpContents", index=1, number=1, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=357,
    serialized_end=403,
)
_sym_db.RegisterEnumDescriptor(_FILEFLAGS)

FileFlags = enum_type_wrapper.EnumTypeWrapper(_FILEFLAGS)
Unknown = 0
OpenRead = 1
OpenModify = 2
CreateRead = 3
CreateModify = 4
Delete = 5
DeleteDelayed = 6
Rename = 7
Truncate = 8
NoFileFlags = 0
DumpContents = 1


_FILE = _descriptor.Descriptor(
    name="File",
    full_name="threemon.File",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ts",
            full_name="threemon.File.ts",
            index=0,
            number=7,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pid",
            full_name="threemon.File.pid",
            index=1,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="procid",
            full_name="threemon.File.procid",
            index=2,
            number=9,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="kind",
            full_name="threemon.File.kind",
            index=3,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="status",
            full_name="threemon.File.status",
            index=4,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="id",
            full_name="threemon.File.id",
            index=5,
            number=4,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="flags",
            full_name="threemon.File.flags",
            index=6,
            number=8,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="srcpath",
            full_name="threemon.File.srcpath",
            index=7,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dstpath",
            full_name="threemon.File.dstpath",
            index=8,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=206,
)

_FILE.fields_by_name["kind"].enum_type = _FILEACCESS
_FILE.fields_by_name["flags"].enum_type = _FILEFLAGS
DESCRIPTOR.message_types_by_name["File"] = _FILE
DESCRIPTOR.enum_types_by_name["FileAccess"] = _FILEACCESS
DESCRIPTOR.enum_types_by_name["FileFlags"] = _FILEFLAGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType(
    "File",
    (_message.Message,),
    dict(
        DESCRIPTOR=_FILE,
        __module__="file_pb2",
        # @@protoc_insertion_point(class_scope:threemon.File)
    ),
)
_sym_db.RegisterMessage(File)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
