# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x08threemon\"\xb5\x01\n\x04\x46ile\x12\n\n\x02ts\x18\x07 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12\"\n\x04kind\x18\x02 \x01(\x0e\x32\x14.threemon.FileAccess\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\n\n\x02id\x18\x04 \x01(\x04\x12\"\n\x05\x66lags\x18\x08 \x01(\x0e\x32\x13.threemon.FileFlags\x12\x0f\n\x07srcpath\x18\x05 \x01(\t\x12\x0f\n\x07\x64stpath\x18\x06 \x01(\t*\x92\x01\n\nFileAccess\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08OpenRead\x10\x01\x12\x0e\n\nOpenModify\x10\x02\x12\x0e\n\nCreateRead\x10\x03\x12\x10\n\x0c\x43reateModify\x10\x04\x12\n\n\x06\x44\x65lete\x10\x05\x12\x11\n\rDeleteDelayed\x10\x06\x12\n\n\x06Rename\x10\x07\x12\x0c\n\x08Truncate\x10\x08*.\n\tFileFlags\x12\x0f\n\x0bNoFileFlags\x10\x00\x12\x10\n\x0c\x44umpContents\x10\x01\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _FILEACCESS._serialized_start=209
  _FILEACCESS._serialized_end=355
  _FILEFLAGS._serialized_start=357
  _FILEFLAGS._serialized_end=403
  _FILE._serialized_start=25
  _FILE._serialized_end=206
# @@protoc_insertion_point(module_scope)
