# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inject.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cinject.proto\x12\x08threemon\"\x82\x01\n\x06Inject\x12\n\n\x02ts\x18\x04 \x01(\r\x12&\n\ttechnique\x18\x01 \x01(\x0e\x32\x13.threemon.Technique\x12\x0e\n\x06srcpid\x18\x02 \x01(\x04\x12\x11\n\tsrcprocid\x18\x05 \x01(\x05\x12\x0e\n\x06\x64stpid\x18\x03 \x01(\x04\x12\x11\n\tdstprocid\x18\x06 \x01(\x05*J\n\tTechnique\x12\x16\n\x12\x43reateRemoteThread\x10\x00\x12\x13\n\x0fShellTrayWindow\x10\x01\x12\x10\n\x0cQueueUserAPC\x10\x02\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inject_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _TECHNIQUE._serialized_start=159
  _TECHNIQUE._serialized_end=233
  _INJECT._serialized_start=27
  _INJECT._serialized_end=157
# @@protoc_insertion_point(module_scope)
