# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutant.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmutant.proto\x12\x08threemon\"w\n\x06Mutant\x12\n\n\x02ts\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x06 \x01(\x05\x12&\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x16.threemon.MutantAction\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t\"u\n\x05\x45vent\x12\n\n\x02ts\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x06 \x01(\x05\x12%\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x15.threemon.EventAction\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t*E\n\x0cMutantAction\x12\x13\n\x0fMutantUndefined\x10\x00\x12\x10\n\x0cMutantCreate\x10\x01\x12\x0e\n\nMutantOpen\x10\x02*i\n\x0b\x45ventAction\x12\x12\n\x0e\x45ventUndefined\x10\x00\x12\r\n\tEventOpen\x10\x01\x12\x11\n\rEventOpenPair\x10\x02\x12\x0f\n\x0b\x45ventCreate\x10\x03\x12\x13\n\x0f\x45ventCreatePair\x10\x04\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mutant_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _MUTANTACTION._serialized_start=266
  _MUTANTACTION._serialized_end=335
  _EVENTACTION._serialized_start=337
  _EVENTACTION._serialized_end=442
  _MUTANT._serialized_start=26
  _MUTANT._serialized_end=145
  _EVENT._serialized_start=147
  _EVENT._serialized_end=264
# @@protoc_insertion_point(module_scope)
