# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x08threemon\"\x85\x01\n\x0bNetworkFlow\x12\n\n\x02ts\x18\x07 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x08 \x01(\x05\x12\r\n\x05proto\x18\x02 \x01(\r\x12\r\n\x05srcip\x18\x03 \x01(\x07\x12\r\n\x05\x64stip\x18\x04 \x01(\x07\x12\x0f\n\x07srcport\x18\x05 \x01(\r\x12\x0f\n\x07\x64stport\x18\x06 \x01(\r\"a\n\x0cMasterSecret\x12\n\n\x02ts\x18\x06 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x07 \x01(\x05\x12\x0c\n\x04\x61rg0\x18\x03 \x01(\x0c\x12\x0c\n\x04\x61rg1\x18\x04 \x01(\x0c\x12\x0c\n\x04\x61rg2\x18\x05 \x01(\x0c\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _NETWORKFLOW._serialized_start=28
  _NETWORKFLOW._serialized_end=161
  _MASTERSECRET._serialized_start=163
  _MASTERSECRET._serialized_end=260
# @@protoc_insertion_point(module_scope)
