# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocess.proto\x12\x08threemon\"\xc2\x01\n\x07Process\x12\n\n\x02ts\x18\x07 \x01(\r\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.threemon.ProcessStatus\x12\x0b\n\x03pid\x18\x02 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12\x0c\n\x04ppid\x18\x03 \x01(\x04\x12\x14\n\x0cparentprocid\x18\n \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x05 \x01(\t\x12\x0c\n\x04orig\x18\x06 \x01(\x08\x12\x13\n\x0b\x65xit_status\x18\x08 \x01(\r*P\n\rProcessStatus\x12\n\n\x06\x43reate\x10\x00\x12\r\n\tTerminate\x10\x01\x12\x0c\n\x08\x45xisting\x10\x02\x12\n\n\x06Ignore\x10\x03\x12\n\n\x06Hidden\x10\x04\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _PROCESSSTATUS._serialized_start=224
  _PROCESSSTATUS._serialized_end=304
  _PROCESS._serialized_start=28
  _PROCESS._serialized_end=222
# @@protoc_insertion_point(module_scope)
