# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="process.proto",
    package="threemon",
    syntax="proto3",
    serialized_options=_b("H\002"),
    serialized_pb=_b(
        "\n\rprocess.proto\x12\x08threemon\"\xc2\x01\n\x07Process\x12\n\n\x02ts\x18\x07 \x01(\r\x12'\n\x06status\x18\x01 \x01(\x0e\x32\x17.threemon.ProcessStatus\x12\x0b\n\x03pid\x18\x02 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12\x0c\n\x04ppid\x18\x03 \x01(\x04\x12\x14\n\x0cparentprocid\x18\n \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x05 \x01(\t\x12\x0c\n\x04orig\x18\x06 \x01(\x08\x12\x13\n\x0b\x65xit_status\x18\x08 \x01(\r*P\n\rProcessStatus\x12\n\n\x06\x43reate\x10\x00\x12\r\n\tTerminate\x10\x01\x12\x0c\n\x08\x45xisting\x10\x02\x12\n\n\x06Ignore\x10\x03\x12\n\n\x06Hidden\x10\x04\x42\x02H\x02\x62\x06proto3"
    ),
)

_PROCESSSTATUS = _descriptor.EnumDescriptor(
    name="ProcessStatus",
    full_name="threemon.ProcessStatus",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="Create", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Terminate", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Existing", index=2, number=2, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Ignore", index=3, number=3, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="Hidden", index=4, number=4, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=224,
    serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_PROCESSSTATUS)

ProcessStatus = enum_type_wrapper.EnumTypeWrapper(_PROCESSSTATUS)
Create = 0
Terminate = 1
Existing = 2
Ignore = 3
Hidden = 4


_PROCESS = _descriptor.Descriptor(
    name="Process",
    full_name="threemon.Process",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ts",
            full_name="threemon.Process.ts",
            index=0,
            number=7,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="status",
            full_name="threemon.Process.status",
            index=1,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pid",
            full_name="threemon.Process.pid",
            index=2,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="procid",
            full_name="threemon.Process.procid",
            index=3,
            number=9,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ppid",
            full_name="threemon.Process.ppid",
            index=4,
            number=3,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="parentprocid",
            full_name="threemon.Process.parentprocid",
            index=5,
            number=10,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="image",
            full_name="threemon.Process.image",
            index=6,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="command",
            full_name="threemon.Process.command",
            index=7,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="orig",
            full_name="threemon.Process.orig",
            index=8,
            number=6,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="exit_status",
            full_name="threemon.Process.exit_status",
            index=9,
            number=8,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=222,
)

_PROCESS.fields_by_name["status"].enum_type = _PROCESSSTATUS
DESCRIPTOR.message_types_by_name["Process"] = _PROCESS
DESCRIPTOR.enum_types_by_name["ProcessStatus"] = _PROCESSSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Process = _reflection.GeneratedProtocolMessageType(
    "Process",
    (_message.Message,),
    dict(
        DESCRIPTOR=_PROCESS,
        __module__="process_pb2",
        # @@protoc_insertion_point(class_scope:threemon.Process)
    ),
)
_sym_db.RegisterMessage(Process)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
