# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="registry.proto",
    package="threemon",
    syntax="proto3",
    serialized_options=_b("H\002"),
    serialized_pb=_b(
        '\n\x0eregistry.proto\x12\x08threemon"\xa7\x01\n\x08Registry\x12\n\n\x02ts\x18\x08 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12$\n\x04kind\x18\x02 \x01(\x0e\x32\x16.threemon.RegistryKind\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0e\n\x06valuei\x18\x05 \x01(\x04\x12\x0e\n\x06values\x18\x06 \x01(\t\x12\x0e\n\x06valued\x18\x07 \x01(\x0c*\x9c\x03\n\x0cRegistryKind\x12\r\n\tCreateKey\x10\x00\x12\x0f\n\x0b\x43reateKeyEx\x10\x01\x12\r\n\tDeleteKey\x10\x02\x12\x10\n\x0c\x45numerateKey\x10\x03\x12\x15\n\x11\x45numerateValueKey\x10\x04\x12\x0c\n\x08\x46lushKey\x10\x05\x12\x12\n\x0eKeyHandleClose\x10\x06\x12\x0b\n\x07LoadKey\x10\x07\x12\x0b\n\x07OpenKey\x10\x08\x12\r\n\tOpenKeyEx\x10\t\x12\x0c\n\x08QueryKey\x10\n\x12\x14\n\x10QueryKeySecurity\x10\x0b\x12\x19\n\x15QueryMultipleValueKey\x10\x0c\x12\x11\n\rQueryValueKey\x10\r\x12\r\n\tRenameKey\x10\x0e\x12\x15\n\x11SetInformationKey\x10\x0f\x12\x12\n\x0eSetKeySecurity\x10\x10\x12\r\n\tUnloadKey\x10\x11\x12\x12\n\x0e\x44\x65leteValueKey\x10\x12\x12\x12\n\x0eSetValueKeyInt\x10\x13\x12\x12\n\x0eSetValueKeyStr\x10\x14\x12\x12\n\x0eSetValueKeyDat\x10\x15\x42\x02H\x02\x62\x06proto3'
    ),
)

_REGISTRYKIND = _descriptor.EnumDescriptor(
    name="RegistryKind",
    full_name="threemon.RegistryKind",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="CreateKey", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="CreateKeyEx", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="DeleteKey", index=2, number=2, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="EnumerateKey", index=3, number=3, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="EnumerateValueKey",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="FlushKey", index=5, number=5, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="KeyHandleClose", index=6, number=6, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="LoadKey", index=7, number=7, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="OpenKey", index=8, number=8, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="OpenKeyEx", index=9, number=9, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="QueryKey", index=10, number=10, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="QueryKeySecurity",
            index=11,
            number=11,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="QueryMultipleValueKey",
            index=12,
            number=12,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="QueryValueKey",
            index=13,
            number=13,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="RenameKey", index=14, number=14, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SetInformationKey",
            index=15,
            number=15,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SetKeySecurity",
            index=16,
            number=16,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="UnloadKey", index=17, number=17, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="DeleteValueKey",
            index=18,
            number=18,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SetValueKeyInt",
            index=19,
            number=19,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SetValueKeyStr",
            index=20,
            number=20,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SetValueKeyDat",
            index=21,
            number=21,
            serialized_options=None,
            type=None,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=199,
    serialized_end=611,
)
_sym_db.RegisterEnumDescriptor(_REGISTRYKIND)

RegistryKind = enum_type_wrapper.EnumTypeWrapper(_REGISTRYKIND)
CreateKey = 0
CreateKeyEx = 1
DeleteKey = 2
EnumerateKey = 3
EnumerateValueKey = 4
FlushKey = 5
KeyHandleClose = 6
LoadKey = 7
OpenKey = 8
OpenKeyEx = 9
QueryKey = 10
QueryKeySecurity = 11
QueryMultipleValueKey = 12
QueryValueKey = 13
RenameKey = 14
SetInformationKey = 15
SetKeySecurity = 16
UnloadKey = 17
DeleteValueKey = 18
SetValueKeyInt = 19
SetValueKeyStr = 20
SetValueKeyDat = 21


_REGISTRY = _descriptor.Descriptor(
    name="Registry",
    full_name="threemon.Registry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ts",
            full_name="threemon.Registry.ts",
            index=0,
            number=8,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pid",
            full_name="threemon.Registry.pid",
            index=1,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="procid",
            full_name="threemon.Registry.procid",
            index=2,
            number=9,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="kind",
            full_name="threemon.Registry.kind",
            index=3,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="status",
            full_name="threemon.Registry.status",
            index=4,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="path",
            full_name="threemon.Registry.path",
            index=5,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="valuei",
            full_name="threemon.Registry.valuei",
            index=6,
            number=5,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="values",
            full_name="threemon.Registry.values",
            index=7,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="valued",
            full_name="threemon.Registry.valued",
            index=8,
            number=7,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=29,
    serialized_end=196,
)

_REGISTRY.fields_by_name["kind"].enum_type = _REGISTRYKIND
DESCRIPTOR.message_types_by_name["Registry"] = _REGISTRY
DESCRIPTOR.enum_types_by_name["RegistryKind"] = _REGISTRYKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Registry = _reflection.GeneratedProtocolMessageType(
    "Registry",
    (_message.Message,),
    dict(
        DESCRIPTOR=_REGISTRY,
        __module__="registry_pb2",
        # @@protoc_insertion_point(class_scope:threemon.Registry)
    ),
)
_sym_db.RegisterMessage(Registry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
