# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x08threemon\"\xa7\x01\n\x08Registry\x12\n\n\x02ts\x18\x08 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\t \x01(\x05\x12$\n\x04kind\x18\x02 \x01(\x0e\x32\x16.threemon.RegistryKind\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0e\n\x06valuei\x18\x05 \x01(\x04\x12\x0e\n\x06values\x18\x06 \x01(\t\x12\x0e\n\x06valued\x18\x07 \x01(\x0c*\x9c\x03\n\x0cRegistryKind\x12\r\n\tCreateKey\x10\x00\x12\x0f\n\x0b\x43reateKeyEx\x10\x01\x12\r\n\tDeleteKey\x10\x02\x12\x10\n\x0c\x45numerateKey\x10\x03\x12\x15\n\x11\x45numerateValueKey\x10\x04\x12\x0c\n\x08\x46lushKey\x10\x05\x12\x12\n\x0eKeyHandleClose\x10\x06\x12\x0b\n\x07LoadKey\x10\x07\x12\x0b\n\x07OpenKey\x10\x08\x12\r\n\tOpenKeyEx\x10\t\x12\x0c\n\x08QueryKey\x10\n\x12\x14\n\x10QueryKeySecurity\x10\x0b\x12\x19\n\x15QueryMultipleValueKey\x10\x0c\x12\x11\n\rQueryValueKey\x10\r\x12\r\n\tRenameKey\x10\x0e\x12\x15\n\x11SetInformationKey\x10\x0f\x12\x12\n\x0eSetKeySecurity\x10\x10\x12\r\n\tUnloadKey\x10\x11\x12\x12\n\x0e\x44\x65leteValueKey\x10\x12\x12\x12\n\x0eSetValueKeyInt\x10\x13\x12\x12\n\x0eSetValueKeyStr\x10\x14\x12\x12\n\x0eSetValueKeyDat\x10\x15\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _REGISTRYKIND._serialized_start=199
  _REGISTRYKIND._serialized_end=611
  _REGISTRY._serialized_start=29
  _REGISTRY._serialized_end=196
# @@protoc_insertion_point(module_scope)
