# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suspicious.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10suspicious.proto\x12\x08threemon\"{\n\nSuspicious\x12\n\n\x02ts\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x06 \x01(\x05\x12(\n\x05\x65vent\x18\x02 \x01(\x0e\x32\x19.threemon.SuspiciousEvent\x12\x0c\n\x04\x61rg1\x18\x03 \x01(\x04\x12\x0c\n\x04\x61rg2\x18\x04 \x01(\x04*\x88\x04\n\x0fSuspiciousEvent\x12\x12\n\x0eUnmapMainImage\x10\x00\x12$\n NtCreateThreadExHideFromDebugger\x10\x01\x12*\n&NtSetInformationThreadHideFromDebugger\x10\x02\x12%\n!NtCreateProcessOtherParentProcess\x10\x03\x12\'\n#NtCreateProcessExOtherParentProcess\x10\x04\x12)\n%NtCreateUserProcessOtherParentProcess\x10\x05\x12\x14\n\x10SetWindowsHookAW\x10\x07\x12\x14\n\x10SetWindowsHookEx\x10\x08\x12\x18\n\x14\x41\x64justPrivilegeToken\x10\x0b\x12\x11\n\rDeletesItself\x10\x0c\x12\x13\n\x0fLoadsDroppedDLL\x10\r\x12\x16\n\x12\x45xecutesDroppedEXE\x10\x0e\x12\x16\n\x12WriteProcessMemory\x10\x11\x12\x14\n\x10SetThreadContext\x10\x12\x12\x17\n\x13\x45numeratesProcesses\x10\x13\x12\x14\n\x10MapViewOfSection\x10\x15\x12\x0f\n\x0bLoadsDriver\x10\x16\x12 \n\x1c\x43mdExeWriteProcessMemorySpam\x10\x17\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suspicious_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _SUSPICIOUSEVENT._serialized_start=156
  _SUSPICIOUSEVENT._serialized_end=676
  _SUSPICIOUS._serialized_start=30
  _SUSPICIOUS._serialized_end=153
# @@protoc_insertion_point(module_scope)
