# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thread.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cthread.proto\x12\x08threemon\"\xb7\x02\n\rThreadContext\x12\n\n\x02ts\x18\x14 \x01(\r\x12\x0e\n\x06srcpid\x18\x01 \x01(\x04\x12\x11\n\tsrcprocid\x18\x15 \x01(\x05\x12\x0e\n\x06\x64stpid\x18\x02 \x01(\x04\x12\x11\n\tdstprocid\x18\x16 \x01(\x05\x12\x0e\n\x06\x64sttid\x18\x03 \x01(\x04\x12\n\n\x02\x61x\x18\x04 \x01(\x04\x12\n\n\x02\x62x\x18\x05 \x01(\x04\x12\n\n\x02\x63x\x18\x06 \x01(\x04\x12\n\n\x02\x64x\x18\x07 \x01(\x04\x12\n\n\x02sp\x18\x08 \x01(\x04\x12\n\n\x02\x62p\x18\t \x01(\x04\x12\n\n\x02si\x18\n \x01(\x04\x12\n\n\x02\x64i\x18\x0b \x01(\x04\x12\n\n\x02r8\x18\x0c \x01(\x04\x12\n\n\x02r9\x18\r \x01(\x04\x12\x0b\n\x03r10\x18\x0e \x01(\x04\x12\x0b\n\x03r11\x18\x0f \x01(\x04\x12\x0b\n\x03r12\x18\x10 \x01(\x04\x12\x0b\n\x03r13\x18\x11 \x01(\x04\x12\x0b\n\x03r14\x18\x12 \x01(\x04\x12\x0b\n\x03r15\x18\x13 \x01(\x04\x42\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thread_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _THREADCONTEXT._serialized_start=27
  _THREADCONTEXT._serialized_end=338
# @@protoc_insertion_point(module_scope)
