# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whois.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bwhois.proto\x12\x08threemon\"\xb7\x01\n\x05Whois\x12$\n\x04\x61rch\x18\x01 \x01(\x0e\x32\x16.threemon.Architecture\x12\x18\n\x02os\x18\x02 \x01(\x0e\x32\x0c.threemon.OS\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05major\x18\x04 \x01(\r\x12\r\n\x05minor\x18\x05 \x01(\r\x12\r\n\x05\x62uild\x18\x06 \x01(\r\x12\x0e\n\x06\x63ommit\x18\x07 \x01(\t\x12\x0f\n\x07is64bit\x18\x08 \x01(\x08\x12\x10\n\x08\x66\x65\x61tures\x18\t \x01(\x04*\x1d\n\x0c\x41rchitecture\x12\x07\n\x03x86\x10\x00\"\x04\x08\x01\x10\x05*\x9c\x01\n\x02OS\x12\x0b\n\x07Win7SP0\x10\x00\x12\x0b\n\x07Win7SP1\x10\x01\x12\n\n\x06Win8_0\x10\x02\x12\n\n\x06Win8_1\x10\x03\x12\x0e\n\nWin10_1507\x10\x04\x12\x0e\n\nWin10_1511\x10\x05\x12\x0e\n\nWin10_1607\x10\x06\x12\x0e\n\nWin10_1703\x10\x07\x12\x0e\n\nWin10_1709\x10\x08\x12\x0e\n\nWin10_1803\x10\t\"\x04\x08\n\x10\nB\x02H\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whois_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\002'
  _ARCHITECTURE._serialized_start=211
  _ARCHITECTURE._serialized_end=240
  _OS._serialized_start=243
  _OS._serialized_end=399
  _WHOIS._serialized_start=26
  _WHOIS._serialized_end=209
# @@protoc_insertion_point(module_scope)
