# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mutant.proto',
  package='threemon',
  syntax='proto3',
  serialized_options=_b('H\002'),
  serialized_pb=_b('\n\x0cmutant.proto\x12\x08threemon\"w\n\x06Mutant\x12\n\n\x02ts\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x06 \x01(\x05\x12&\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x16.threemon.MutantAction\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t\"u\n\x05\x45vent\x12\n\n\x02ts\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06procid\x18\x06 \x01(\x05\x12%\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x15.threemon.EventAction\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0c\n\x04path\x18\x04 \x01(\t*E\n\x0cMutantAction\x12\x13\n\x0fMutantUndefined\x10\x00\x12\x10\n\x0cMutantCreate\x10\x01\x12\x0e\n\nMutantOpen\x10\x02*i\n\x0b\x45ventAction\x12\x12\n\x0e\x45ventUndefined\x10\x00\x12\r\n\tEventOpen\x10\x01\x12\x11\n\rEventOpenPair\x10\x02\x12\x0f\n\x0b\x45ventCreate\x10\x03\x12\x13\n\x0f\x45ventCreatePair\x10\x04\x42\x02H\x02\x62\x06proto3')
)

_MUTANTACTION = _descriptor.EnumDescriptor(
  name='MutantAction',
  full_name='threemon.MutantAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MutantUndefined', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MutantCreate', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MutantOpen', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=266,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_MUTANTACTION)

MutantAction = enum_type_wrapper.EnumTypeWrapper(_MUTANTACTION)
_EVENTACTION = _descriptor.EnumDescriptor(
  name='EventAction',
  full_name='threemon.EventAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EventUndefined', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EventOpen', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EventOpenPair', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EventCreate', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EventCreatePair', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=337,
  serialized_end=442,
)
_sym_db.RegisterEnumDescriptor(_EVENTACTION)

EventAction = enum_type_wrapper.EnumTypeWrapper(_EVENTACTION)
MutantUndefined = 0
MutantCreate = 1
MutantOpen = 2
EventUndefined = 0
EventOpen = 1
EventOpenPair = 2
EventCreate = 3
EventCreatePair = 4



_MUTANT = _descriptor.Descriptor(
  name='Mutant',
  full_name='threemon.Mutant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='threemon.Mutant.ts', index=0,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='threemon.Mutant.pid', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procid', full_name='threemon.Mutant.procid', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='threemon.Mutant.action', index=3,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='threemon.Mutant.status', index=4,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='threemon.Mutant.path', index=5,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=145,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='threemon.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='threemon.Event.ts', index=0,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='threemon.Event.pid', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procid', full_name='threemon.Event.procid', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='threemon.Event.action', index=3,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='threemon.Event.status', index=4,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='threemon.Event.path', index=5,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=264,
)

_MUTANT.fields_by_name['action'].enum_type = _MUTANTACTION
_EVENT.fields_by_name['action'].enum_type = _EVENTACTION
DESCRIPTOR.message_types_by_name['Mutant'] = _MUTANT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.enum_types_by_name['MutantAction'] = _MUTANTACTION
DESCRIPTOR.enum_types_by_name['EventAction'] = _EVENTACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mutant = _reflection.GeneratedProtocolMessageType('Mutant', (_message.Message,), dict(
  DESCRIPTOR = _MUTANT,
  __module__ = 'mutant_pb2'
  # @@protoc_insertion_point(class_scope:threemon.Mutant)
  ))
_sym_db.RegisterMessage(Mutant)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'mutant_pb2'
  # @@protoc_insertion_point(class_scope:threemon.Event)
  ))
_sym_db.RegisterMessage(Event)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
