# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thread.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='thread.proto',
  package='threemon',
  syntax='proto3',
  serialized_options=_b('H\002'),
  serialized_pb=_b('\n\x0cthread.proto\x12\x08threemon\"\xb7\x02\n\rThreadContext\x12\n\n\x02ts\x18\x14 \x01(\r\x12\x0e\n\x06srcpid\x18\x01 \x01(\x04\x12\x11\n\tsrcprocid\x18\x15 \x01(\x05\x12\x0e\n\x06\x64stpid\x18\x02 \x01(\x04\x12\x11\n\tdstprocid\x18\x16 \x01(\x05\x12\x0e\n\x06\x64sttid\x18\x03 \x01(\x04\x12\n\n\x02\x61x\x18\x04 \x01(\x04\x12\n\n\x02\x62x\x18\x05 \x01(\x04\x12\n\n\x02\x63x\x18\x06 \x01(\x04\x12\n\n\x02\x64x\x18\x07 \x01(\x04\x12\n\n\x02sp\x18\x08 \x01(\x04\x12\n\n\x02\x62p\x18\t \x01(\x04\x12\n\n\x02si\x18\n \x01(\x04\x12\n\n\x02\x64i\x18\x0b \x01(\x04\x12\n\n\x02r8\x18\x0c \x01(\x04\x12\n\n\x02r9\x18\r \x01(\x04\x12\x0b\n\x03r10\x18\x0e \x01(\x04\x12\x0b\n\x03r11\x18\x0f \x01(\x04\x12\x0b\n\x03r12\x18\x10 \x01(\x04\x12\x0b\n\x03r13\x18\x11 \x01(\x04\x12\x0b\n\x03r14\x18\x12 \x01(\x04\x12\x0b\n\x03r15\x18\x13 \x01(\x04\x42\x02H\x02\x62\x06proto3')
)




_THREADCONTEXT = _descriptor.Descriptor(
  name='ThreadContext',
  full_name='threemon.ThreadContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='threemon.ThreadContext.ts', index=0,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srcpid', full_name='threemon.ThreadContext.srcpid', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srcprocid', full_name='threemon.ThreadContext.srcprocid', index=2,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstpid', full_name='threemon.ThreadContext.dstpid', index=3,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstprocid', full_name='threemon.ThreadContext.dstprocid', index=4,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dsttid', full_name='threemon.ThreadContext.dsttid', index=5,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ax', full_name='threemon.ThreadContext.ax', index=6,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bx', full_name='threemon.ThreadContext.bx', index=7,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cx', full_name='threemon.ThreadContext.cx', index=8,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dx', full_name='threemon.ThreadContext.dx', index=9,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sp', full_name='threemon.ThreadContext.sp', index=10,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bp', full_name='threemon.ThreadContext.bp', index=11,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='si', full_name='threemon.ThreadContext.si', index=12,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='di', full_name='threemon.ThreadContext.di', index=13,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r8', full_name='threemon.ThreadContext.r8', index=14,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r9', full_name='threemon.ThreadContext.r9', index=15,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r10', full_name='threemon.ThreadContext.r10', index=16,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r11', full_name='threemon.ThreadContext.r11', index=17,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r12', full_name='threemon.ThreadContext.r12', index=18,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r13', full_name='threemon.ThreadContext.r13', index=19,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r14', full_name='threemon.ThreadContext.r14', index=20,
      number=18, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r15', full_name='threemon.ThreadContext.r15', index=21,
      number=19, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=338,
)

DESCRIPTOR.message_types_by_name['ThreadContext'] = _THREADCONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThreadContext = _reflection.GeneratedProtocolMessageType('ThreadContext', (_message.Message,), dict(
  DESCRIPTOR = _THREADCONTEXT,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:threemon.ThreadContext)
  ))
_sym_db.RegisterMessage(ThreadContext)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
